
/**
* Chương trình quản lý nhân viên
*
* @author  Trương A Xin
* @version 1.0
* @since   14/12/2020
*/
package quanlinhansu;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author truon
 */
public class MainWindow extends javax.swing.JFrame {

    private DSNhanVien danhsachNhanVien = new DSNhanVien();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttGroup = new javax.swing.ButtonGroup();
        bttGroup_sex = new javax.swing.ButtonGroup();
        label_name = new javax.swing.JLabel();
        label_country = new javax.swing.JLabel();
        label_sex = new javax.swing.JLabel();
        line_name = new javax.swing.JTextField();
        line_country = new javax.swing.JTextField();
        radio_huanluyenvien = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_show = new javax.swing.JTable();
        label_birthday = new javax.swing.JLabel();
        label_intodate = new javax.swing.JLabel();
        line_birthday = new javax.swing.JTextField();
        line_intoDate = new javax.swing.JTextField();
        radio_cauthu = new javax.swing.JRadioButton();
        label_vitri = new javax.swing.JLabel();
        label_soluottran = new javax.swing.JLabel();
        label_banthang = new javax.swing.JLabel();
        label_luongthoathuan = new javax.swing.JLabel();
        line_vitri = new javax.swing.JTextField();
        line_soluottran = new javax.swing.JTextField();
        line_banthang = new javax.swing.JTextField();
        line_luongthoathuan = new javax.swing.JTextField();
        line_luongcoban = new javax.swing.JTextField();
        line_phucap = new javax.swing.JTextField();
        label_namkinhnghiem = new javax.swing.JLabel();
        label_luongcoban = new javax.swing.JLabel();
        label_phucap = new javax.swing.JLabel();
        line_kinhnghiem = new javax.swing.JTextField();
        btt_add = new javax.swing.JButton();
        btt_edit = new javax.swing.JButton();
        btt_del = new javax.swing.JButton();
        label_ID = new javax.swing.JLabel();
        line_ID = new javax.swing.JTextField();
        radio_sex_nam = new javax.swing.JRadioButton();
        radio_sex_nu = new javax.swing.JRadioButton();
        label_hesoluong = new javax.swing.JLabel();
        line_hesoluong = new javax.swing.JTextField();
        btt_find = new javax.swing.JButton();
        btt_luongCaoNhat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí nhân viên");

        label_name.setText("Tên");

        label_country.setText("Quốc tịch");

        label_sex.setText("Giới tính");

        line_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line_nameActionPerformed(evt);
            }
        });

        bttGroup.add(radio_huanluyenvien);
        radio_huanluyenvien.setText("Huấn luyện viên");
        radio_huanluyenvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_huanluyenvienActionPerformed(evt);
            }
        });

        tabel_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "Quốc tịch", "Giới tính", "Ngày sinh", "Ngày vào"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_showMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_show);

        label_birthday.setText("Ngày sinh");

        label_intodate.setText("Ngày vào");

        bttGroup.add(radio_cauthu);
        radio_cauthu.setSelected(true);
        radio_cauthu.setText("Cầu thủ");
        radio_cauthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_cauthuActionPerformed(evt);
            }
        });

        label_vitri.setText("Vị trí thi đấu");

        label_soluottran.setText("Số lượt trận tham gia");

        label_banthang.setText("Số bàn thắng");

        label_luongthoathuan.setText("Lương thỏa thuận");

        line_luongcoban.setEnabled(false);

        line_phucap.setEnabled(false);

        label_namkinhnghiem.setText("Số năm kinh nghiệm");

        label_luongcoban.setText("Lương cơ bản");

        label_phucap.setText("Phụ cấp");

        line_kinhnghiem.setEnabled(false);

        btt_add.setText("Thêm");
        btt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_addActionPerformed(evt);
            }
        });

        btt_edit.setText("Sửa");
        btt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_editActionPerformed(evt);
            }
        });

        btt_del.setText("Xóa");
        btt_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_delActionPerformed(evt);
            }
        });

        label_ID.setText("ID");

        bttGroup_sex.add(radio_sex_nam);
        radio_sex_nam.setSelected(true);
        radio_sex_nam.setText("Nam");

        bttGroup_sex.add(radio_sex_nu);
        radio_sex_nu.setText("Nữ");

        label_hesoluong.setText("Hệ số lương");

        line_hesoluong.setEnabled(false);

        btt_find.setText("Tìm");
        btt_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_findActionPerformed(evt);
            }
        });

        btt_luongCaoNhat.setText("Lương cao nhất");
        btt_luongCaoNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_luongCaoNhatActionPerformed(evt);
            }
        });

        jLabel1.setText("truongaxin © 2020");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label_country)
                                    .addGap(18, 18, 18)
                                    .addComponent(line_country, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label_name)
                                        .addComponent(label_ID))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(line_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(line_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_sex)
                                            .addComponent(label_birthday))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_intodate)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(line_intoDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_sex_nam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_sex_nu)))))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_cauthu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_luongthoathuan)
                                    .addComponent(label_banthang)
                                    .addComponent(label_soluottran)
                                    .addComponent(label_vitri))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(line_banthang, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(line_soluottran)
                                    .addComponent(line_vitri)
                                    .addComponent(line_luongthoathuan))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_huanluyenvien)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_namkinhnghiem)
                                        .addGap(18, 18, 18)
                                        .addComponent(line_kinhnghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_phucap)
                                            .addComponent(label_luongcoban)
                                            .addComponent(label_hesoluong))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(line_phucap, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(line_luongcoban, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                            .addComponent(line_hesoluong, javax.swing.GroupLayout.Alignment.LEADING)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btt_del, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(btt_find, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btt_luongCaoNhat)))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_ID)
                            .addComponent(line_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_name)
                            .addComponent(line_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(line_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_country))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_sex)
                            .addComponent(radio_sex_nam)
                            .addComponent(radio_sex_nu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_birthday)
                            .addComponent(line_birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radio_huanluyenvien)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_namkinhnghiem)
                                    .addComponent(line_kinhnghiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_luongcoban)
                                    .addComponent(line_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_phucap)
                                    .addComponent(line_phucap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_hesoluong)
                                    .addComponent(line_hesoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(line_vitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(line_soluottran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(line_banthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_banthang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(line_luongthoathuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_luongthoathuan)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radio_cauthu)
                        .addGap(23, 23, 23)
                        .addComponent(label_vitri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_soluottran)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_intodate)
                    .addComponent(line_intoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btt_add)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btt_del)
                        .addComponent(btt_edit)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btt_find)
                    .addComponent(btt_luongCaoNhat))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_cauthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_cauthuActionPerformed
        // TODO add your handling code here:
        if (this.radio_cauthu.isSelected()) {
            this.line_kinhnghiem.setEnabled(false);
            this.line_luongcoban.setEnabled(false);
            this.line_phucap.setEnabled(false);
            this.line_hesoluong.setEnabled(false);

            this.line_banthang.setEnabled(true);
            this.line_soluottran.setEnabled(true);
            this.line_luongthoathuan.setEnabled(true);
            this.line_vitri.setEnabled(true);
        }

    }//GEN-LAST:event_radio_cauthuActionPerformed

    private void line_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_line_nameActionPerformed

    private void btt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_addActionPerformed
        // TODO add your handling code here:
        this.addNhanVien();
    }//GEN-LAST:event_btt_addActionPerformed

    private void radio_huanluyenvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_huanluyenvienActionPerformed
        // TODO add your handling code here:
        if (this.radio_huanluyenvien.isSelected()) {
            this.line_kinhnghiem.setEnabled(true);
            this.line_luongcoban.setEnabled(true);
            this.line_phucap.setEnabled(true);
            this.line_hesoluong.setEnabled(true);

            this.line_banthang.setEnabled(false);
            this.line_soluottran.setEnabled(false);
            this.line_luongthoathuan.setEnabled(false);
            this.line_vitri.setEnabled(false);
        }
    }//GEN-LAST:event_radio_huanluyenvienActionPerformed

    private void tabel_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_showMouseClicked
        // TODO add your handling code here:
        // Lấy vị trí hàng, lấy được ID
        javax.swing.JTable source;
        source = (javax.swing.JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        String id = (String) source.getModel().getValueAt(row, 0);
        // Đổ data vào form
        NhanVien a = this.danhsachNhanVien.my_dict.get(id);
        this.fillData2Fields(a);
    }//GEN-LAST:event_tabel_showMouseClicked

    private void btt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_editActionPerformed
        // TODO add your handling code here:
        if (danhsachNhanVien.my_dict.containsKey(this.line_ID.getText())) {
            try {
                if (danhsachNhanVien.my_dict.containsKey(this.line_ID.getText()) == true) {
                    SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
                    String ID = this.line_ID.getText();
                    String name = this.line_name.getText();
                    boolean sex = this.radio_sex_nam.isSelected();
                    String country = this.line_country.getText();
                    Date birthday = fm.parse(this.line_birthday.getText());
                    Date intoday = fm.parse(this.line_intoDate.getText());
                    if (this.radio_cauthu.isSelected()) {
                        String vitri = this.line_vitri.getText();
                        int soLuotTran = Integer.parseInt(this.line_soluottran.getText());
                        int soBanThang = Integer.parseInt(this.line_banthang.getText());
                        double luongThoaThuan = Double.parseDouble(this.line_luongthoathuan.getText());
                        CauThu a = new CauThu(ID, name, vitri, sex, birthday, intoday, vitri, soLuotTran, soBanThang, luongThoaThuan);
                        this.danhsachNhanVien.suaNhanVien(this.line_ID.getText(), a);
                        this.loadTable();
                    } else {
                        int soNamKinhNghiem = Integer.parseInt(this.line_kinhnghiem.getText());
                        double luongCoBan = Double.parseDouble(this.line_luongcoban.getText());
                        double phuCap = Double.parseDouble(this.line_phucap.getText());
                        double heSoLuong = Double.parseDouble(this.line_hesoluong.getText());
                        HuanLuyenVien a = new HuanLuyenVien(ID, name, country, sex, birthday, intoday, soNamKinhNghiem, luongCoBan, phuCap, heSoLuong);
                        this.danhsachNhanVien.suaNhanVien(this.line_ID.getText(), a);
                        this.loadTable();
                    }
                } else {
                    // khi khác id, hỏi người dùng có muốn add hay không
                    int result = javax.swing.JOptionPane.showConfirmDialog((java.awt.Component) null, "Bạn vừa chỉnh sửa ID, bạn có muốn thêm Nhân Viên này không?",
                            "alert", javax.swing.JOptionPane.OK_CANCEL_OPTION);
                    if (result == 0) {
                        this.addNhanVien();
                    }
                }

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Có gì đó sai sai");
            }
        }
        
    }//GEN-LAST:event_btt_editActionPerformed

    private void btt_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_delActionPerformed
        // TODO add your handling code here:
        if (this.line_ID.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Bạn chưa nhập ID\nCần ID để xóa!");
        }
        else if (this.danhsachNhanVien.my_dict.containsKey(this.line_ID.getText()) == false) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID không tồn tại");
        }
        else{
            String ID = this.line_ID.getText();
            this.danhsachNhanVien.xoaNhanVien(ID);
            this.loadTable();
            this.cleanBasicFields();
            this.cleanCauThuFields();
            this.cleanHuanLuyenVienFields();
            javax.swing.JOptionPane.showMessageDialog(this, "Đã xóa nhân viên có ID: "+ID);
        }
    }//GEN-LAST:event_btt_delActionPerformed

    private void btt_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_findActionPerformed
        // TODO add your handling code here:
        String result = (String)JOptionPane.showInputDialog(
               this,
               "Nhập tên nhân viên", 
               "Tìm kiếm nhân viên",            
               JOptionPane.PLAIN_MESSAGE,
               null,            
               null, 
               ""
            );
        System.out.println(result);
        for(NhanVien a: this.danhsachNhanVien.my_dict.values()){
            if (a.getTenNhanVien().equals(result)) {
                this.cleanBasicFields();
                this.cleanCauThuFields();
                this.cleanHuanLuyenVienFields();
                this.fillData2Fields(a);
                return;
            }
        }
        if (result != null) {
            JOptionPane.showMessageDialog(this, "Không tin thấy nhân viên với tên: "+result);
        }
    }//GEN-LAST:event_btt_findActionPerformed

    private void btt_luongCaoNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_luongCaoNhatActionPerformed
        // TODO add your handling code here:
        String id = this.danhsachNhanVien.luongCaoNhat();
        if (id == null) {
            JOptionPane.showMessageDialog(this, "Chưa có nhân viên nào hết :D");
            return;
        }
        NhanVien a = this.danhsachNhanVien.my_dict.get(id);
        if (a instanceof CauThu){
            CauThu b = (CauThu) a;
            String msg = "Nhân viên có mức lương cao nhất là "+b.getTenNhanVien()+"\n"
                    + "Với mức lương: "+String.valueOf(b.tinhLuong());
            JOptionPane.showMessageDialog(this, msg);
        }
        else {
            HuanLuyenVien b = (HuanLuyenVien) a;
            String msg = "Nhân viên có mức lương cao nhất là "+b.getTenNhanVien()+"\n"
                    + "Với mức lương: "+String.valueOf(b.tinhLuong());
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_btt_luongCaoNhatActionPerformed

    private void fillData2Fields(NhanVien a) {
        this.line_ID.setText(a.getID());
        this.line_name.setText(a.getTenNhanVien());
        this.line_country.setText(a.getQuocTich());
        if (a.isGioiTinh()) {
            this.radio_sex_nam.setSelected(true);
        } else {
            this.radio_sex_nu.setSelected(true);
        }
        this.line_birthday.setText(a.getNgaySinh());
        this.line_intoDate.setText(a.getNgayVaolam());
        if (a instanceof CauThu) {
            CauThu b = (CauThu) a;
            this.setGroupCauThuEnable();
            this.setGroupHuanLuyenVienDisable();
            this.line_vitri.setText(b.getViTriThiDauString());
            this.line_luongthoathuan.setText((String.valueOf(b.getLuongThoaThuan())));
            this.line_soluottran.setText(String.valueOf(b.getSoLuotTranThamGia()));
            this.line_banthang.setText(String.valueOf(b.getSoBanThang()));
        } else {
            HuanLuyenVien b = (HuanLuyenVien) a;
            this.setGroupHuanLuyenVienEnable();
            this.setGroupCauThuDisable();
            this.line_kinhnghiem.setText(String.valueOf(b.getSoNamKinhNghiem()));
            this.line_luongcoban.setText(String.valueOf(b.getLuongCoBan()));
            this.line_phucap.setText(String.valueOf(b.getPhuCap()));
            this.line_hesoluong.setText(String.valueOf(b.getHeSoLuong()));
        }
    }
    
    private boolean checkValid() {
        return true;
    }
    
    private void addNhanVien() {
        try {
            if (danhsachNhanVien.my_dict.containsKey(this.line_ID.getText()) == false) {
                SimpleDateFormat fm = new SimpleDateFormat("dd/MM/yyyy");
                String ID = this.line_ID.getText();
                String name = this.line_name.getText();
                boolean sex = this.radio_sex_nam.isSelected();
                String country = this.line_country.getText();
                Date birthday = fm.parse(this.line_birthday.getText());
                Date intoday = fm.parse(this.line_intoDate.getText());
                if (this.radio_cauthu.isSelected()) {
                    String vitri = this.line_vitri.getText();
                    int soLuotTran = Integer.parseInt(this.line_soluottran.getText());
                    int soBanThang = Integer.parseInt(this.line_banthang.getText());
                    double luongThoaThuan = Double.parseDouble(this.line_luongthoathuan.getText());
                    CauThu a = new CauThu(ID, name, country, sex, birthday, intoday, vitri, soLuotTran, soBanThang, luongThoaThuan);
                    danhsachNhanVien.themNhanVien(ID, a);
                    this.loadTable();
//                    this.addRow(a);
                } else {
                    int soNamKinhNghiem = Integer.parseInt(this.line_kinhnghiem.getText());
                    double luongCoBan = Double.parseDouble(this.line_luongcoban.getText());
                    double phuCap = Double.parseDouble(this.line_phucap.getText());
                    double heSoLuong = Double.parseDouble(this.line_hesoluong.getText());
                    HuanLuyenVien a = new HuanLuyenVien(ID, name, country, sex, birthday, intoday, soNamKinhNghiem, luongCoBan, phuCap, heSoLuong);
                    danhsachNhanVien.themNhanVien(ID, a);
                    this.loadTable();
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID bị trùng, xin nhập lại ID");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Có gì đó sai sai");
        }
    }

    private void loadTable() {
        System.out.println("load table");
        Vector Col = new Vector();
        Col.addElement("ID");
        Col.addElement("Tên");
        Col.addElement("Quốc tịch");
        Col.addElement("Giới tính");
        Col.addElement("Ngày Sinh");
        Col.addElement("Ngày Vào");
        Vector data = new Vector();
        for (String k : this.danhsachNhanVien.my_dict.keySet()) {
            NhanVien a = this.danhsachNhanVien.my_dict.get(k);
            Vector nhanvien = new Vector();
            nhanvien.addElement(a.getID());
            nhanvien.addElement(a.getTenNhanVien());
            nhanvien.addElement(a.getQuocTich());
            nhanvien.addElement(a.getGioiTinh());
            nhanvien.addElement(a.getNgaySinh());
            nhanvien.addElement(a.getNgayVaolam());
            data.addElement(nhanvien);
        }
        this.tabel_show.setModel(new DefaultTableModel(data, Col));
    }

    private void setGroupCauThuEnable() {
        this.radio_cauthu.setSelected(true);
        this.line_luongthoathuan.setEnabled(true);
        this.line_banthang.setEnabled(true);
        this.line_soluottran.setEnabled(true);
        this.line_vitri.setEnabled(true);
    }

    private void setGroupCauThuDisable() {
        this.radio_cauthu.setSelected(false);
        this.line_luongthoathuan.setEnabled(false);
        this.line_banthang.setEnabled(false);
        this.line_soluottran.setEnabled(false);
        this.line_vitri.setEnabled(false);
    }

    private void setGroupHuanLuyenVienEnable() {
        this.radio_huanluyenvien.setSelected(true);
        this.line_kinhnghiem.setEnabled(true);
        this.line_luongcoban.setEnabled(true);
        this.line_phucap.setEnabled(true);
        this.line_hesoluong.setEnabled(true);
    }

    private void setGroupHuanLuyenVienDisable() {
        this.radio_huanluyenvien.setSelected(false);
        this.line_kinhnghiem.setEnabled(false);
        this.line_luongcoban.setEnabled(false);
        this.line_phucap.setEnabled(false);
        this.line_hesoluong.setEnabled(false);
    }

    private void cleanCauThuFields() {
        this.line_vitri.setText("");
        this.line_soluottran.setText("");
        this.line_banthang.setText("");
        this.line_luongthoathuan.setText("");
    }
    
    private void cleanHuanLuyenVienFields() {
        this.line_kinhnghiem.setText("");
        this.line_luongcoban.setText("");
        this.line_phucap.setText("");
        this.line_hesoluong.setText("");
    }
    
    private void cleanBasicFields() {
        this.line_ID.setText("");
        this.line_name.setText("");
        this.line_country.setText("");
        this.line_birthday.setText("");
        this.line_intoDate.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bttGroup;
    private javax.swing.ButtonGroup bttGroup_sex;
    private javax.swing.JButton btt_add;
    private javax.swing.JButton btt_del;
    private javax.swing.JButton btt_edit;
    private javax.swing.JButton btt_find;
    private javax.swing.JButton btt_luongCaoNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_ID;
    private javax.swing.JLabel label_banthang;
    private javax.swing.JLabel label_birthday;
    private javax.swing.JLabel label_country;
    private javax.swing.JLabel label_hesoluong;
    private javax.swing.JLabel label_intodate;
    private javax.swing.JLabel label_luongcoban;
    private javax.swing.JLabel label_luongthoathuan;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_namkinhnghiem;
    private javax.swing.JLabel label_phucap;
    private javax.swing.JLabel label_sex;
    private javax.swing.JLabel label_soluottran;
    private javax.swing.JLabel label_vitri;
    private javax.swing.JTextField line_ID;
    private javax.swing.JTextField line_banthang;
    private javax.swing.JTextField line_birthday;
    private javax.swing.JTextField line_country;
    private javax.swing.JTextField line_hesoluong;
    private javax.swing.JTextField line_intoDate;
    private javax.swing.JTextField line_kinhnghiem;
    private javax.swing.JTextField line_luongcoban;
    private javax.swing.JTextField line_luongthoathuan;
    private javax.swing.JTextField line_name;
    private javax.swing.JTextField line_phucap;
    private javax.swing.JTextField line_soluottran;
    private javax.swing.JTextField line_vitri;
    private javax.swing.JRadioButton radio_cauthu;
    private javax.swing.JRadioButton radio_huanluyenvien;
    private javax.swing.JRadioButton radio_sex_nam;
    private javax.swing.JRadioButton radio_sex_nu;
    private javax.swing.JTable tabel_show;
    // End of variables declaration//GEN-END:variables
}
